services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: jobber
      POSTGRES_PASSWORD: jobber
      POSTGRES_DB: jobber_auth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_jobber:/var/lib/postgresql/data

volumes:
  postgres_data_jobber:
    driver: local